version: "3"
services:
  web:
    image: chandradckap/magento:2.4.5-p1
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
    - PHP_MEMORY_LIMIT=3G
    networks:
      - mynetwork
    depends_on:
      - mysql
      - elasticsearch
      - redis

  mysql:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    networks:
      - mynetwork
    volumes:
      - /var/www/mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=300M
    ports:
      - "8080:80"
    links:
      - mysql:db
    depends_on:
      - mysql
    networks:
      - mynetwork

  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - mynetwork

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
